/*SS
form=quaked;
class=func_button;
group=struct;
desc= When a button is touched, it 
	moves some distance in the direction 
	of its angle, triggers all of its 
	targets, waits some time\ then returns 
	to its original position where it can 
	be triggered again;
flag= 0\pushed\Pushed\
	Button is pushed already;
flag= 1\blabla\Blabla\
	blablavla;
key=  target\dir\0\
	Move direction\Determines the opening direction;
*/

/*SS
form=quaked;
class=item_armor;
group=armor;
min=-16 -16 -16;
max=16 16 16;
desc= Gives 20% damage absorb;
key=  mark\list\\
	Armor Mark\Mark of armor\
		0\Normal mark\
		1\Rotten\
 		2\Strong defence;
*/

/*
 NOTE: #list# tag always must be in the beginning of line!
*/
